language: node_js
node_js:
  - '0.12'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  global:
    secure: IIjGgpOAZ2R9jsjdE6ozwaNDeGyOz9vxj+wOyVjkS6BFcV3l76oRQOgPES38NonWm/Qw0pzQ7AbW7Oek2FKkKtSfdpSVu+0s34XgM3ULrZKHUey4ZlLp2emS4yVknVO6uzqoChpwu0JCyud71AXA5BMe3t5j0Ttaj4OAq2AMm9Y=
